resources:
- minio/minio.yaml
- odh/codeflare-stack.yaml
- odh/custom-notebooks.yaml
- demo-manifests/fraud-detection.yaml
- demo-manifests/object-detection.yaml
- demo-manifests/huggingface-demo.yaml
- odh/modelmesh/custom-serving-runtimes.yaml