---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: codeserver-
resources:
  - pod.yaml
images:
  - name: codeserver-workbench
    newName: quay.io/opendatahub/workbench-images
    newTag: codeserver-ubi9-python-3.11
