kind: Secret
apiVersion: v1
metadata:
  name: pachyderm-s3-secret
stringData:
  access-id: S3-access-id
  access-secret: S3-secret-key
  bucket: pachyderm
  region: us-east-2
  custom-endpoint: http://s3.openshift-storage.svc.cluster.local
