kind: ConfigMap
apiVersion: v1
metadata:
  name: odh-jupyterhub-sizes
  namespace: odh-applications
  labels:
    app.kubernetes.io/part-of: jupyterhub
    component.opendatahub.io/name: jupyterhub
    jupyterhub: singleuser-profiles
    opendatahub.io/component: 'true'
  annotations:
    kfctl.kubeflow.io/kfdef-instance: opendatahub.odh-applications
data:
  jupyterhub-singleuser-profiles.yaml: |
    sizes:
    - name: Small
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          memory: 2Gi
          cpu: 2
    - name: Medium
      resources:
        requests:
          memory: 2Gi
          cpu: 2
        limits:
          memory: 4Gi
          cpu: 4
    - name: Large
      resources:
        requests:
          memory: 4Gi
          cpu: 4
        limits:
          memory: 8Gi
          cpu: 8
    - name: X-Large
      resources:
        requests:
          memory: 8Gi
          cpu: 8
        limits:
          memory: 16Gi
          cpu: 16
    - name: XX-Large
      resources:
        requests:
          memory: 16Gi
          cpu: 10
        limits:
          memory: 32Gi
          cpu: 32
